### PR TITLE
Packages & baseline

### PR DESCRIPTION
**Pull request by bjrne**

### CODE REVIEW

**Comment by Baschdl** [comment]
@HPI-SWA-Teaching/2017-student-team-01 Tests are fixed, please review this commit

**Review by feeds — APPROVED** [review]
Well, the tests work :)

**Comment by bjrne** [comment]
This PR includes changes to the browser as well as UI and model fragments, is this intended? Or was it a failure of the squeak+git workflow? Other wise the title would be misleading and the PR hard to review @Baschdl

**Comment by Baschdl** [comment]
@bjrne You mean something like the CommitOutputSpike? [https://github.com/HPI-SWA-Teaching/SWT17-Project-01/blame/9ec9561f7e2b12c1d3597a7fc42578ba8cf7054d/GANA-Core.package/CommitOutputSpike.class/instance/printBranches..st](https://github.com/HPI-SWA-Teaching/SWT17-Project-01/blame/9ec9561f7e2b12c1d3597a7fc42578ba8cf7054d/GANA-Core.package/CommitOutputSpike.class/instance/printBranches..st)

Or about what changes do you speak?

**Pull request merged**
