### PR TITLE
Add search-bar

### LINKED ISSUE #31: US-10: Add text field to type search terms

### PR DESCRIPTION
**Pull request by Blubl**
closes #31

### CODE REVIEW

**Review by feeds — CHANGES_REQUESTED** [review]
Ok, I resolved the merge conflicts. 

But anywas ... write a small test :) - it should be easy though. 
E.g change the input in the model and check wether the search term is actuall the input afterwards

**Comment by Baschdl** [comment]
There should be a "use newest date" to merge squeak `methodProperties` files

**Comment by feeds** [comment]
I think the image merges like that, but since the pull request uses the standard git merges there are these problems. Maybe we should merge manually in the image on a branch merge?

**Comment by Baschdl** [comment]
What do you mean with "merge manually in the image"?

**Comment by feeds** [comment]
if you want to merge x into master, and the pull request is approved, go to the image, merge master into x and then you should be able automatically merge on github, right?

**Review by feeds — APPROVED** [review]

**Comment by Baschdl** [comment]
@feeds "This pull request is closed, but the search-bar branch has unmerged commits." Why did you merge this PR by hand?

**Pull request closed without merging**
