### PR TITLE
New graph implementation

### PR DESCRIPTION
**Pull request by bjrne**

### CODE REVIEW

**Comment by feeds** [comment]
Did you find the reason for the test fail?

**Comment by bjrne** [comment]
Not yet. I will look for that this evening.

**Comment by Baschdl** [comment]
@bjarne 
 ✗ #testSearchAbbreviatedHashFromStart (23ms)
TestFailure: Assertion failed
GanaBrowserTest(TestCase)>>signalFailure:
GanaBrowserTest(TestCase)>>assert:
GanaBrowserTest>>assertCommitListIncludesAll:
GanaBrowserTest>>testSearchAbbreviatedHashFromStart ...assertCommitListIncludesAll: { version1 . version2 }
GanaBrowserTest(TestCase)>>performTest

Did you change the list? Do the tests pass locally?

**Comment by bjrne** [comment]
I know what travis says, that was the test that Freya was talking about. I just asked for a code review beyond what is obviously wrong.

**Comment by bjrne** [comment]
Weird changes coming from nowhere. These changes will be merged in #56.

**Pull request closed without merging**
