### PR TITLE
Adapt appveyor setup

### PR DESCRIPTION
**Pull request by Baschdl**
Adapt appveyor setup after information in smalltalkCI README

### CODE REVIEW

**Comment by Baschdl** [comment]
[The build fails on Squeak-5.0 on Windows](https://ci.appveyor.com/project/Baschdl/swt17-project-01/build/1.0.26/job/cd47tajr0hp2i3qq) despite the fact that it passes on Squeak-5.1 and trunk on Windows and on all versions on Ubuntu and Mac. We configured the baseline right but it's the old `Error: 'BaselineOfGANA' not registered (loaded)`.
@fniephaus Do you know this problem? Is it connected to smalltalkCI?

**Comment by fniephaus** [comment]
It looks like [the failing job](https://ci.appveyor.com/project/Baschdl/swt17-project-01/build/1.0.26/job/cd47tajr0hp2i3qq#L233) was unable to load the latest version of Metacello (see [L233](https://ci.appveyor.com/project/Baschdl/swt17-project-01/build/1.0.26/job/cd47tajr0hp2i3qq#L233)).
This sometimes happens because of network connectivity problems.
What happens when you restart the build?

**Comment by Baschdl** [comment]
The build ran the third time and it still fails because of the BaselineOfMonticello

**Comment by fniephaus** [comment]
Interesting. Please file an issue [here](https://github.com/hpi-swa/smalltalkCI/issues/new) and deactivate `Squeak-5.0` in your `appveyor.yml` for the time being. There might be something wrong with Metacello for Squeak-5.0 on Windows, but I currently don't have the time to look into this.

**Review by Blubl — APPROVED** [review]
all ok

**Pull request merged**
